---
title: "Printability analysis with hydraulic diameter"
author: "irw"
date: "Created 20230630 -- Last compiled `r format(Sys.Date())`"
always_allow_html: false
output:
  pdf_document:
    toc: yes
    keep_tex: true
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
params:
  verbose: yes
changes:
- "20230630 - Created. Adapted from report template"
editor_options: 
  chunk_output_type: inline
---

```{r, include=FALSE}
if (params$verbose) {
  knitr::opts_chunk$set(
    echo = TRUE,
    warning = TRUE,
    message = FALSE
  )
} else {
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE
  )
}

knitr::opts_chunk$set(fig.width=120*1/25.4, fig.height=90*1/25.4, dpi=500)
```

```{r, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

```{r, child='notes.txt', eval=F}
```

```{r, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

```{r}
# Setup chunk

parent <- "feature/folder/"

make_path <- function(local_path, parent_dir = parent) {
  path = here::here(paste0(parent_dir, local_path))
}

# Load libraries
library(tidyverse)
library(here)
library(jsonlite)
library(kableExtra)
library(plotly)
library(glue)
library(pracma)

source(here::here("resources/plot/print_ggplot.R"))
source(here::here("resources/plot/plot_interactive.R"))
source(here::here("lobe/scripts/lattice_models_wp.R"))

knitr::asis_output("# Session Info")
sessionInfo()
```

```{r, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

---
# Analysis


```{r, fig.width=6, fig.height=4.5, dpi=300}
plot <- list(
  r = seq(0.1, 0.2, length.out = 5),
  lc = seq(1, 2, length.out = 8)
) %>% 
  cross_df() %>% 
  mutate(
    rstar = r/lc,
    dh = hydraulic_diameter_dimensionless_wp(rstar)*lc) %>% 
  ggplot(aes(x = lc, y = r)) + 
  geom_contour_filled(data = list(
    r = seq(0.1, 0.2, length.out = 5) %>% c(0.09, 0.21),
    lc = seq(1, 2, length.out = 8) %>% c(0.9, 2.1)
  ) %>% 
    cross_df() %>% 
    mutate(
      rstar = r/lc,
      dh = hydraulic_diameter_dimensionless_wp(rstar)*lc),
  aes(x = lc, y = r, z = dh), 
  breaks = seq(from = 0.0, to = 1.8, by = 0.2))+
  geom_point(aes(size = rstar)) +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_x_continuous(breaks = c(seq(1, 2, length.out = 5))) +
  scale_y_continuous(breaks = c(seq(0.1, 0.2, length.out = 5))) +
  coord_cartesian(expand = F, xlim = c(0.9, 2.1), ylim = c(0.09, 0.21)) +
  labs(x = expression(l[c]  (mm)), y = "r (mm)") +
  guides(size = guide_legend(title = "r*", title.hjust = 0.5),
         fill = guide_legend(title = expression(d[h] (mm)), title.hjust = 0.5))

plot %>% print(width = 6, height = 4.5, dpi = 300)

```



  
  