---
title: "Breathing Validation - TIDAL 2"
author: "irw"
date: "Created 2023mmDD -- Last compiled `r format(Sys.Date())`"
always_allow_html: false
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
    keep_tex: false
params:
  verbose: yes
changes:
- "Adapted from report template"
---

```{r, include = F}

child_chunk = knitr::opts_knit$get("child")

```


```{r, eval = !child_chunk, include=FALSE}
if (params$verbose) {
  knitr::opts_chunk$set(
    echo = TRUE,
    warning = TRUE,
    message = FALSE
  )
} else {
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE
  )
}



knitr::opts_chunk$set(fig.width=120*1/25.4, fig.height=90*1/25.4, dpi=500)
```

```{r, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

```{r, eval = !child_chunk}
# Setup chunk

make_path <- function(local_path, parent_dir = parent) {
  path = here::here(paste0(parent_dir, "/", local_path))
}

# Load libraries
library(tidyverse)
library(here)
library(jsonlite)
library(kableExtra)
library(plotly)
library(glue)
library(pracma)
library(car)

source(here::here("resources/plot/print_ggplot.R"))
source(here::here("resources/plot/plot_interactive.R"))

source(here::here("resources/reports/table_functions.R"))
source(here::here("breathing/scripts/breaths_table.R"))
source(here::here("breathing/scripts/breathing_analysis.R"))

knitr::asis_output("# Session Info")
sessionInfo()
```

```{r, eval = !child_chunk, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

```{r}
parent <- "deposition/20231130-full-lung/data/"
data_folder = "231130-b15-8d/data/"
name = strsplit(data_folder, "/")[[1]][1]

read_flow_folder(data_folder, 10, name) %>% 
  plot_flow_index_r() %>% 
  plot_interactive()

min = 17758
max = 23481

get_data(name) %>% 
  slice(min:max) %>%
  plot_flow_index_r() %>% 
  plot_interactive()
```
```{r}
breaths = 10
tibble(
    peak = rep(seq_len(breaths), each=2),
    maneuver = rep(c("i","e"), times = breaths)
) %>% 
    make_peaks_index_r(name = name)

peak_indices <- c(18243, 18437, 18753, 18944, 19259, 19449, 19767, 19957, 20272, 20464, 20780, 20973, 21287, 21479, 21795, 21985, 22300, 22491, 22808)

get_peaks(name) %>% 
  mutate(
    start = c(min, peak_indices),
    end = c(peak_indices, max)
  ) %>% 
  make_peaks_index_r(name)

get_peaks(name) %>% pmap_dfr(get_breath_data) %>% make_breaths(name, .)

get_breaths(name) %>% 
  subset(peak > min(peak) & peak < max(peak)) %>% 
  plot_flow_time() %>% 
  plot_interactive()

get_breaths(name) %>% 
  subset(peak > min(peak) & peak < max(peak)) %>% 
  plot_flow_volume() %>% 
  plot_interactive()
```
```{r, results='asis'}
get_breaths(name) %>% 
  print_breath_summary(formatted_only = !params$verbose)
```

```{r}
# Export Rds
archive_path <- make_path(paste0("breaths0_", name, ".Rds"))

get_breaths(name) %>% 
  subset(peak > min(peak) & peak < max(peak)) %>% 
  group_by(peak) %>%
  zero_minutes() %>%
  saveRDS(., archive_path)


# Example overlay plot
# get_breaths(name) %>% 
#     subset(peak > min(peak) & peak < max(peak)) %>% 
#     group_by(peak) %>% 
#     zero_minutes() %>% 
#     plot_flow_time(use_alpha=T, alpha=0.7) %>% 
#     plot_interactive()
```