---
title: "Load full lung deposition trials"
author: "irw"
date: "Created 2023mmDD -- Last compiled `r format(Sys.Date())`"
always_allow_html: false
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
    keep_tex: true
params:
  verbose: yes
changes:
- "Adapted from report template"
---

```{r, include = F}

child_chunk = knitr::opts_knit$get("child")

```


```{r, eval = !child_chunk, include=FALSE}
if (params$verbose) {
  knitr::opts_chunk$set(
    echo = TRUE,
    warning = TRUE,
    message = FALSE
  )
} else {
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE
  )
}



knitr::opts_chunk$set(fig.width=120*1/25.4, fig.height=90*1/25.4, dpi=500)
```

```{r, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

```{r, eval = !child_chunk}
# Setup chunk

# Load libraries
library(tidyverse)
library(here)
library(jsonlite)
library(kableExtra)
library(plotly)
library(glue)
library(pracma)
library(car)

source(here::here("resources/utils/make_path.R"))
source(here::here("resources/plot/print_ggplot.R"))
source(here::here("resources/plot/plot_interactive.R"))

knitr::asis_output("# Session Info")
sessionInfo()
```

```{r, eval = !child_chunk, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

```{r}
dates <- c(
  "20231127",
  "20231130",
  "20231204",
  "20231218",
  "20231220",
  "20231222",
  "20240123",
  "20240126",
  "20240221"
)

import_lung_summary <- function(date) {
  summary_file <- make_path(paste0("data/summary-full-lung-", date, ".csv"), 
            parent_dir = paste0("deposition/",date,"-full-lung/"))
  
  df <- read_csv(summary_file)
  
  df <- df %>% mutate(date = date)
  
  return(df)
}

full_lung_aggregate <- lapply(dates, import_lung_summary) %>% 
  bind_rows()
```

