---
title: "Comparison to KDEP, MPPD simulations"
author: "irw"
date: "Last compiled `r format(Sys.Date())`"
always_allow_html: false
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
    keep_tex: false
params:
  verbose: no
editor_options: 
  chunk_output_type: inline
---

```{r, include = F}

child_chunk = knitr::opts_knit$get("child")

```


```{r, eval = !child_chunk, include=FALSE}
if (params$verbose) {
  knitr::opts_chunk$set(
    echo = TRUE,
    warning = TRUE,
    message = FALSE
  )
} else {
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE
  )
}



knitr::opts_chunk$set(fig.width=120*1/25.4, fig.height=90*1/25.4, 
                      dpi=500, fig.retina = 1)
```


```{r, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```

```{r, eval = !child_chunk}
# Setup chunk

# Load libraries
library(tidyverse)
library(here)
library(jsonlite)
library(kableExtra)
library(plotly)
library(glue)
library(pracma)
library(car)

source(here::here("resources/utils/make_path.R"))
source(here::here("resources/plot/print_ggplot.R"))
source(here::here("resources/plot/plot_interactive.R"))

knitr::asis_output("# Session Info")
sessionInfo()
```

```{r, eval = !child_chunk, echo=FALSE}
if (knitr::is_latex_output()) {
knitr::asis_output("\\newpage")
}
```


```{r}
parent <- "deposition/mppd-kdep"
```

```{r}
## Manually enter reference values

kdep_data_vec <- c(
  "et1" = 0.274504,
  "et2" = 0.236541,
  "BB" = 3.92e-2,
  "bb" = 3.94e-2,
  "AI" = 0.130894,
  "Total" = 0.720589
)

kdep_data <- kdep_data_vec %>% 
  enframe(name = "lobe", value = "frac_total") %>% 
  mutate(
    pct_dep = frac_total / kdep_data_vec["Total"] * 100
  )

mppd_data_shallow_vec <- c(
  "ru" = 0.0519,
  "rm" = 0.0254,
  "rl" = 0.1029,
  "lu" = 0.0508,
  "ll" = 0.1021,
  "deposited" = 0.7163
)

mppd_data_shallow <- mppd_data_shallow_vec %>% 
  enframe(name = "lobe", value = "frac_total") %>% 
  mutate(
    pct_dep = frac_total / mppd_data_shallow_vec["deposited"] * 100
  )

mppd_data_deep_vec <- c(
  "ru" = 0.0604,
  "rm" = 0.0296,
  "rl" = 0.1220,
  "lu" = 0.0602,
  "ll" = 0.1209,
  "deposited" = 0.7849
) 

mppd_data_deep <- mppd_data_deep_vec %>% 
  enframe(name = "lobe", value = "frac_total") %>% 
  mutate(
    pct_dep = frac_total / mppd_data_deep_vec["deposited"] * 100
  )
```

